/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CarrinhoContext`; params?: Router.UnknownInputParams; } | { pathname: `/ComandaItens`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `/carrinho`; params?: Router.UnknownInputParams; } | { pathname: `/comanda`; params?: Router.UnknownInputParams; } | { pathname: `/comandaFechada`; params?: Router.UnknownInputParams; } | { pathname: `/copa`; params?: Router.UnknownInputParams; } | { pathname: `/cozinha`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/produto`; params?: Router.UnknownInputParams; } | { pathname: `/produtoCadastro`; params?: Router.UnknownInputParams; } | { pathname: `/relatorio`; params?: Router.UnknownInputParams; } | { pathname: `/relatorioDiario`; params?: Router.UnknownInputParams; } | { pathname: `/relatorioPeriodo`; params?: Router.UnknownInputParams; } | { pathname: `/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CarrinhoContext`; params?: Router.UnknownOutputParams; } | { pathname: `/ComandaItens`; params?: Router.UnknownOutputParams; } | { pathname: `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/cardapio`; params?: Router.UnknownOutputParams; } | { pathname: `/carrinho`; params?: Router.UnknownOutputParams; } | { pathname: `/comanda`; params?: Router.UnknownOutputParams; } | { pathname: `/comandaFechada`; params?: Router.UnknownOutputParams; } | { pathname: `/copa`; params?: Router.UnknownOutputParams; } | { pathname: `/cozinha`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/pagamento`; params?: Router.UnknownOutputParams; } | { pathname: `/produto`; params?: Router.UnknownOutputParams; } | { pathname: `/produtoCadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/relatorio`; params?: Router.UnknownOutputParams; } | { pathname: `/relatorioDiario`; params?: Router.UnknownOutputParams; } | { pathname: `/relatorioPeriodo`; params?: Router.UnknownOutputParams; } | { pathname: `/usuarios`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/CarrinhoContext${`?${string}` | `#${string}` | ''}` | `/ComandaItens${`?${string}` | `#${string}` | ''}` | `/cadastro${`?${string}` | `#${string}` | ''}` | `/cardapio${`?${string}` | `#${string}` | ''}` | `/carrinho${`?${string}` | `#${string}` | ''}` | `/comanda${`?${string}` | `#${string}` | ''}` | `/comandaFechada${`?${string}` | `#${string}` | ''}` | `/copa${`?${string}` | `#${string}` | ''}` | `/cozinha${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/pagamento${`?${string}` | `#${string}` | ''}` | `/produto${`?${string}` | `#${string}` | ''}` | `/produtoCadastro${`?${string}` | `#${string}` | ''}` | `/relatorio${`?${string}` | `#${string}` | ''}` | `/relatorioDiario${`?${string}` | `#${string}` | ''}` | `/relatorioPeriodo${`?${string}` | `#${string}` | ''}` | `/usuarios${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CarrinhoContext`; params?: Router.UnknownInputParams; } | { pathname: `/ComandaItens`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `/carrinho`; params?: Router.UnknownInputParams; } | { pathname: `/comanda`; params?: Router.UnknownInputParams; } | { pathname: `/comandaFechada`; params?: Router.UnknownInputParams; } | { pathname: `/copa`; params?: Router.UnknownInputParams; } | { pathname: `/cozinha`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/produto`; params?: Router.UnknownInputParams; } | { pathname: `/produtoCadastro`; params?: Router.UnknownInputParams; } | { pathname: `/relatorio`; params?: Router.UnknownInputParams; } | { pathname: `/relatorioDiario`; params?: Router.UnknownInputParams; } | { pathname: `/relatorioPeriodo`; params?: Router.UnknownInputParams; } | { pathname: `/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
